### ISSUE TITLE
retrieve error?

### ISSUE THREAD

**Issue by IceskYsl** [andyw8/pocket-ruby#14]
```
session: #<Rack::Session::Abstract::SessionHash:0x00000101103f18>
127.0.0.1 - - [06/Jan/2015:15:56:31 +0800] "GET / HTTP/1.1" 200 262 0.0061
Faraday::ClientError - the server responded with status 500:
    /www/1sters/pocket-ruby/lib/faraday/raise_pocket_error.rb:24:in `on_complete'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
    /www/1sters/pocket-ruby/lib/faraday/pocket_oauth.rb:15:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
    /www/1sters/pocket-ruby/lib/pocket/client/retrieve.rb:7:in `retrieve'
    demo-server.rb:67:in `block in <main>'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `block in spawn_threadpool'
Unexpected error while processing request: undefined method `join' for #<String:0x0000010138a7f0>
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `call'
    /Users/iceskysl/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `block in spawn_threadpool'

```

**Comment by jasonngpt** [comment]
Hello @IceskYsl 

Are you using the demo-server.rb straight or is the consumer_key updated? 

Did you manage to Connect with Pocket, authorizing the application before doing the retrieve?

Will be great if you include steps taken to replicate that retrieval error?

Thanks!

**Comment by jasonngpt** [comment]
Hello @IceskYsl 

Still facing problems?

**Comment by jasonngpt** [comment]
Closing this. Please re-open it if it is still an issue. Thanks!
